USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/samsung/j7xelte/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := exynos5
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := j7xelte

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 352321536
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 417333248
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 329882096
BOARD_USERDATAIMAGE_PARTITION_SIZE := 127775277056
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_CACHEIMAGE_PARTITION_SIZE := 220200960
TARGET_PREBUILT_KERNEL := device/samsung/j7xelte/prebuilt/kernel

RECOVERY_VARIANT := twrp

BOARD_HAS_NO_SELECT_BUTTON := true
